#This Travis config template file was taken from https://github.com/FriendsOfCake/travis
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
  - php: 5.5
    env: PHPCS=1 DEFAULT=0

  - php: 5.5
    env: COVERALLS=1 DEFAULT=0

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev

before_script:
  - mkdir config && mkdir config/Environment && cp -r example/config/Environment/* config/Environment
  - cp config/Environment/environment.local.php.default config/Environment/environment.local.php
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require cakephp/cakephp-codesniffer:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"

  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then phpunit --stderr --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  irc: "irc.freenode.org#wasabi"
  email: false
  slack:
    secure: QMWzCAOBt69kNN5rFKltkOG26/u5uYtIo0xO1ecowtiMofPeaaNGkrdlP2aaOun5Qg7q0/tTCe7CLp0l4xPulPDOOpqrc3GDosJImgkn7n6/QqzGMr4pUgxe454STDm++H/XbYf7tS6AUTNJjbhIu19+5AX++Xm1DeogDH21VXo=
